### ISSUE TITLE
Problems get awslogs running

### ISSUE THREAD

**Issue by asd1** [jorgebastida/awslogs#100]
I have an Ubuntu 14.04 server that I am trying get CloudWatch running on. I followed all the steps, I think, and when I attempt to start the awslogs service I  the following errors in the awslogs.log:

_Traceback (most recent call last):
  File "/var/awslogs/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/var/awslogs/local/lib/python2.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/var/awslogs/local/lib/python2.7/site-packages/botocore/session.py", line 25, in <module>
    import botocore.config
  File "/var/awslogs/local/lib/python2.7/site-packages/botocore/config.py", line 18, in <module>
    from botocore.compat import six
  File "/var/awslogs/local/lib/python2.7/site-packages/botocore/compat.py", line 15, in <module>
    import datetime
ImportError: No module named datetime_

I can see these are Python errors but why am I getting them? Does anyone have any ideas what might not be setup properly?

Thanks

**Comment by jorgebastida** [comment]
This error looks unrelated to awslogs. Not been able to import ``datetime`` looks like a more serious issue with how your environment is configured as that a built-in package of python. Sorry I can't give you any more light on this!
