### ISSUE TITLE
Broken pipe when piping to head

### ISSUE THREAD

**Issue by bdarfler** [jorgebastida/awslogs#101]
`awslogs get dashboard --start='1m ago' --profile prod | head -n10`
```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.7.0
Python: 2.7.12 (default, Oct 11 2016, 05:20:59) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
boto3 version: 1.4.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'dashboard', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '1m ago', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'dashboard', '--start=1m ago', '--profile', 'prod']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 185, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
================================================================================
```

**Comment by jorgebastida** [comment]
Fixed https://github.com/jorgebastida/awslogs/pull/128
