### ISSUE TITLE
awslogs groups

### ISSUE THREAD

**Issue by leejonggun** [jorgebastida/awslogs#108]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
boto3 version: 1.4.4
Platform: Darwin-15.6.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 61, in __init__
    region_name=self.aws_region
  File "/usr/local/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
================================================================================

**Comment by kadrach** [comment]
Try setting `region` in the `default` section in your `~/.aws/config` or set the environment variable `AWS_DEFAULT_REGION` to your region (e.g. `us-east-1`).
