### ISSUE TITLE
Not able to use awslogs due to pkg_resources.DistributionNotFound: gevent>=1.0

### ISSUE THREAD

**Issue by bobber205** [jorgebastida/awslogs#11]
For some reason, awslogs always throws the following error upon `awslogs` or any other command

```
Traceback (most recent call last):
  File "/usr/local/bin/awslogs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: gevent>=1.0
```

Any idea on what could be wrong? This tool looks super awesome and I'd love to be able to use it :)

(Configured ~/.aws using awscli)

**Comment by bobber205** [comment]
I solved this running running

```
sudo apt-get install python-dev
sudo pip install gevent
```

first was needed to get second to finish compiling
