### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by nasiman** [jorgebastida/awslogs#110]
```
Version: 0.8.0
Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
boto3 version: 1.4.4
Platform: Linux-3.13.0-100-generic-x86_64-with-Ubuntu-14.04-trusty
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': 'ALL', 'watch': False, 'aws_region': 'us-east-1', 'aws_session_token': 'SENSITIVE', 'start': '1d', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'log_group_name': '/aws/lambda/processor', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/processor', '-s1d']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 184, in consumer
    print(' '.join(output))
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 105-106: ordinal not in range(128)
```

**Comment by nasiman** [comment]
Duplicate of https://github.com/jorgebastida/awslogs/issues/99. Closing.
