### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when --no-ssl-verification

### ISSUE THREAD

**Issue by abject18** [jorgebastida/awslogs#117]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:38:22) [MSC v.1600 32 bit (Intel)]
boto3 version: 1.4.4
Platform: Windows-8-6.2.9200
Config: {'aws_region': None, 'aws_secret_access_key': 'SENSITIVE', 'aws_access_key_id': 'SENSITIVE', 'log_group_prefix': None, 'aws_profile': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'func': 'list_groups'}
Args: ['C:\\Users\\lmccarthy\\Envs\\awslogs\\Scripts\\awslogs', 'groups', '--no-ssl-verification', '--profile', 'default']

Traceback (most recent call last):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\util\ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\python34\Lib\ssl.py", line 364, in wrap_socket
    _context=self)
  File "c:\python34\Lib\ssl.py", line 578, in __init__
    self.do_handshake()
  File "c:\python34\Lib\ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\adapters.py", line 370, in send
    timeout=timeout
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 574, in urlopen
    raise SSLError(e)
botocore.vendored.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\awslogs\core.py", line 194, in list_groups
    for group in self.get_groups():
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\awslogs\core.py", line 208, in get_groups
    for page in paginator.paginate(**kwargs):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\endpoint.py", line 170, in _send_request
    success_response, exception):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\lmccarthy\envs\awslogs\lib\site-packages\botocore\vendored\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
================================================================================

**Comment by jorgebastida** [comment]
This looks like a botocore related bug/issue
