### ISSUE TITLE
Using of --start frequently causes crashes 

### ISSUE THREAD

**Issue by bobber205** [jorgebastida/awslogs#12]
Using any input for --start causing weird crashes like this
```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.0.2
Python: 2.7.3 (default, Dec 18 2014, 19:10:20) 
[GCC 4.6.3]
boto version: 2.38.0
Platform: Linux-3.2.0-23-generic-x86_64-with-Ubuntu-12.04-precise
Config: {'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': u'sidekiq-ip-10-158-29-134-i-bb7a6f4a', 'aws_region': u'us-east-1', 'watch': False, 'start': u'1m', 'log_group_name': u'services', 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'services', 'sidekiq-ip-10-158-29-134-i-bb7a6f4a', '--start=1m']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 121, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 236, in list_logs
    pool.join()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 100, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
================================================================================
```

in this particular instance I did

awslogs get services someserverthing --start='1m'

Any advice? :)

**Comment by bjudson** [comment]
I'm getting this exception on every request, whether I use `--start` or not. Also should note that it returns results before crashing.

**Comment by jorgebastida** [comment]
I've just pushed a new version (0.1.0) to pypi which should fix this issue.
https://pypi.python.org/pypi/awslogs/0.1.0
