### ISSUE TITLE
NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by jimzucker** [jorgebastida/awslogs#120]
Command run: awslogs groups --profile fundpaas-staging

Note: the profile works with aws logs directly, ie this works:  aws logs get-log-events * --profile fundpaas-staging * --log-group-name ECSLogGroup-stage  --log-stream-name Staging/webapp-fundpaas/d30292dc-7d71-430d-b6a6-d986eda88ded

Output:

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.11 (default, Jan 18 2016, 22:11:38)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
boto3 version: 1.4.4
Platform: Darwin-16.1.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups', '--profile', 'fundpaas-staging']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 194, in list_groups
    for group in self.get_groups():
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 208, in get_groups
    for page in paginator.paginate(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python2.7/site-packages/botocore/auth.py", line 316, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials
================================================================================

**Comment by jimzucker** [comment]
Update: I found if I run as sudo on my mac it works.

➜  awslogs git:(master) ✗ sudo awslogs groups --profile fundpaas-staging
/aws/codebuild/master
/aws/lambda/CloudTrailListener
/aws/lambda/GSSlackbotLink
ECSLogGroup-sandbox
ECSLogGroup-stage
ECSLogGroup-stress-testing
RDSOSMetrics
