### ISSUE TITLE
Broken Pipe (noisy exit)

### ISSUE THREAD

**Issue by samba** [jorgebastida/awslogs#122]
When passing through `less` and similar, the pipe may be closed before `awslogs` completes its output, in which case it gets noisy.

```
Traceback (most recent call last):
  File "/var/task/service/kinesis.py", line 85, in parseRecords
    message = json.loads(payload.strip())
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
```

--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.10 (default, Jul 30 2016, 19:40:32)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
boto3 version: 1.4.4
Platform: Darwin-16.4.0-x86_64-i386-64bit
Config: `{'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'REDACTED', 'log_stream_name': 'ALL', 'aws_region': 'us-west-2', 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '14d', 'aws_profile': 'SENSITIVE', 'filter_pat
tern': 'ERROR', 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}`
Args: `['/usr/local/bin/awslogs', 'get', '-s', '14d', 'REDACTED', '--filter-pattern=ERROR']`

```
Traceback (most recent call last):
  File "/Users/samba/Library/Python/2.7/lib/python/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/Users/samba/Library/Python/2.7/lib/python/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/Users/samba/Library/Python/2.7/lib/python/site-packages/awslogs/core.py", line 185, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```

**Comment by jorgebastida** [comment]
Fixed https://github.com/jorgebastida/awslogs/pull/128
