### ISSUE TITLE
MacOS Darwin : Get logs with a wildcard stream

### ISSUE THREAD

**Issue by stemlaur** [jorgebastida/awslogs#131]
Hello, 

I get an error when I try to query streams with a wildcard at the beginning of the selector.

Is it something supported right now ?

Regards

```
Version: 0.8.0
Python: 2.7.12 (default, Oct 11 2016, 05:16:02)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
boto3 version: 1.4.4
Platform: Darwin-16.4.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'prod-tomcat-app', 'log_stream_name': '*requests*', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'prod-tomcat-app', '*requests*']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 75, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 67, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: nothing to repeat
```

**Comment by jadekler** [comment]
+1, problem for me, too

**Comment by jadekler** [comment]
@stemlaur I believe you can use `ALL` instead of wildcar

**Comment by jorgebastida** [comment]
It is not supported at the moment, no. You could use ``ALL`` and do further filtering with grep. Will consider this for future releases
