### ISSUE TITLE
Unclear how to use -filter-pattern for json logs

### ISSUE THREAD

**Issue by Fodoj** [jorgebastida/awslogs#134]
I can't make --filter-patern option work for me. 

First of all, al my messages are json. So I tried this filter, which works when I put it in AWS CW Logs Console:

```
awslogs get my-logs i-1234567890 --query=message --start='1 hour' --aws-region us-east-1 -filter-pattern='{ $.systemdUnit= "my-app.service" }'
```

I get this error back:

```
Traceback (most recent call last):
  File "/usr/bin/awslogs", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 136, in consumer
    for event in generator():
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 123, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/home/kshirinkin/.local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kshirinkin/.local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the FilterLogEvents operation: Invalid filter pattern
```

Suprisingly, if I try to filter by one word, I get no results:

```
awslogs get my-logs i-1234567890 --query=message --start='1 hour' --aws-region us-east-1 -filter-pattern='my-app'
```

Which is, again, a different result than what I get in AWS Console. 

And if I try to use wildcards, I get the same error again:

```
awslogs get my-logs i-1234567890 --query=message --start='1 hour' --aws-region us-east-1 -filter-pattern='*my-app*'
```

error:

```
Traceback (most recent call last):
  File "/usr/bin/awslogs", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 136, in consumer
    for event in generator():
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 123, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/home/kshirinkin/.local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kshirinkin/.local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the FilterLogEvents operation: Invalid filter pattern
```

**Comment by Fodoj** [comment]
Omg, my bad, I apologize for my stupidity. 

I've used `-filter-pattern` instead of `--filter-pattern`. Now it works. 

But hey, at least I can confirm that json filtering works :)

**Comment by hayd** [comment]
What is the correct syntax here?
