### ISSUE TITLE
traceback thrown when using ' | head -1'

### ISSUE THREAD

**Issue by mjh1** [jorgebastida/awslogs#135]
The command seemed to succeed however a traceback was thrown asking me to raise a bug 👍 
```
~ awslogs get -G --timestamp -s 1d /LOG -f 'MY SEARCH' | head -1
i-086385936675 2017-05-14T10:13:39.780Z WARN	server	comment	2017-05-14	10:13:39	-	-	-	-	-	2113652.316	alive_Out2	-	-	-	-	-	-	-	REST OF LOG LINE....

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
boto3 version: 1.4.4
Platform: Darwin-16.4.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': True, 'output_group_enabled': False, 'end': None, 'log_group_name': '/LOG', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '1d', 'aws_profile': 'SENSITIVE', 'filter_pattern': 'MY SEARCH', 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '-G', '--timestamp', '-s', '1d', '/LOG', '-f', 'MY SEARCH']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 185, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
================================================================================
```

**Comment by jorgebastida** [comment]
This has been fixed on master
