### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jghaines** [jorgebastida/awslogs#139]
awslogs asked me to raise this, but I don't think it is a serious issue. Most likely I hit Ctrl-C. Maybe an exception need to be caught and handled more gracefully.

```
awslogs get --start "30m ago" /aws/lambda/<function-name> | grep <event id> |less

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.13 (default, Apr 12 2017, 12:00:44) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.41)]
boto3 version: 1.4.4
Platform: Darwin-16.6.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': '/aws/lambda/ccoe-aws-account-utils-AutoTagFunction-9MU80HVL0PW2', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '30m ago', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '--start', '30m ago', '/aws/lambda/ccoe-aws-account-utils-AutoTagFunction-9MU80HVL0PW2']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 185, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
================================================================================

```

**Comment by jorgebastida** [comment]
Yep, next version should ignore this. Thanks
