### ISSUE TITLE
awslogs bug you must specify a region

### ISSUE THREAD

**Issue by twellspring** [jorgebastida/awslogs#141]
Bug discovered on a  Mac OS X Yosemite workstation. 
the ENV variable AWS_REGION=us-east-2  is also set. 
Installed via PIP.  Tried both `sudo  pip install awslogs --ignore-installed six` and `sudo  pip install awslogs `

```
Bens-Air:~ bsawyer$ awslogs --aws-region=us-east-2 groups

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.8.0
Python: 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
boto3 version: 1.4.4
Platform: Darwin-14.5.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', '--aws-region=us-east-2', 'groups']

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 61, in __init__
    region_name=self.aws_region
  File "/Library/Python/2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 281, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Library/Python/2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Library/Python/2.7/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 354, in resolve
    service_name, region_name)
  File "/Library/Python/2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Library/Python/2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
================================================================================
Bens-Air:~ bsawyer$ ```

**Comment by jorgebastida** [comment]
Interesting... the only thing I can think of is that you have an empty/invalid value in the ``AWS_REGION`` env variable. https://github.com/jorgebastida/awslogs/blob/master/awslogs/bin.py#L55 Could you please check that?

**Comment by Martijn02** [comment]
This has to do with the argument order. I can replicate this without setting any environment variable.

```
# awslogs --aws-region=eu-west-1 groups # Same error
# awslogs groups --aws-region=eu-west-1 # Works fine
# awslogs groups --aws-region eu-west-1 # Works fine

# awslogs --aws-region eu-west-1 groups
usage: awslogs [ get | groups | streams ]
awslogs: error: invalid choice: 'eu-west-1' (choose from 'get', 'groups', 'streams')
```


If I set the AWS_REGION environment variable to an empty value, I get an different error:
```
ValueError: Invalid endpoint: https://logs..amazonaws.com
```
