### ISSUE TITLE
Issue watching logs using STS role from Windows 7 with Python 3.5.1

### ISSUE THREAD

**Issue by danizen** [jorgebastida/awslogs#147]
I suspect that this is just due to using Windows.    I'm actually using MSYS2 (Git bash) from within Cmder as well, which may be the confusion.   I have some notes from a long time back about Python's default encoding in this environment, as this was my main reservation about developers using Windows for development, but CentOS 7 for deployment.

```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
boto3 version: 1.4.5
Platform: Windows-7-6.1.7601-SP1
Config: {'output_stream_enabled': True, 'aws_profile': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'color_enabled': True, 'output_timestamp_enabled': False, 'filter_pattern': None, 'watch': False, 'output_group_enabled': True, 'aws_access_key_id': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'log_group_name': 'NLM-INT-var-log-messages', 'log_stream_name': 'dantest', 'end': None, 'aws_region': None, 'query': None, 'start': '1d', 'aws_secret_access_key': 'SENSITIVE', 'func': 'list_logs'}
Args: ['C:\\Users\\davisda4\\PythonEnvs\\nlmcatutils\\Scripts\\awslogs', 'get', 'NLM-INT-var-log-messages', 'dantest', '--start=1d']

Traceback (most recent call last):
  File "c:\users\davisda4\pythonenvs\nlmcatutils\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\users\davisda4\pythonenvs\nlmcatutils\lib\site-packages\awslogs\core.py", line 196, in list_logs
    consumer()
  File "c:\users\davisda4\pythonenvs\nlmcatutils\lib\site-packages\awslogs\core.py", line 185, in consumer
    print(' '.join(output))
  File "c:\users\davisda4\pythonenvs\nlmcatutils\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 210: character maps to <undefined>
================================================================================
```

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
