### ISSUE TITLE
Error getting logs

### ISSUE THREAD

**Issue by alex88** [jorgebastida/awslogs#16]
I've this exception:

```
$ awslogs  awslogs get /aws/lambda/myfunction ALL -s1d
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 519, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 186, in _raw_events_queue_consumer
    timestamp, line = self.raw_events_queue.peek(timeout=1)
  File "/usr/local/lib/python2.7/site-packages/gevent/queue.py", line 305, in peek
    self.getters.discard(waiter)
AttributeError: 'collections.deque' object has no attribute 'discard'
<Greenlet at 0x1087fab90: <bound method AWSLogs._raw_events_queue_consumer of <awslogs.core.AWSLogs object at 0x10875b150>>> failed with AttributeError


================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.0.3
Python: 2.7.10 (default, Jul 20 2015, 10:27:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.57.2)]
boto version: 2.38.0
Platform: Darwin-15.0.0-x86_64-i386-64bit
Config: {'output_group_enabled': True, 'end': None, 'log_group_name': u'/aws/lambda/myfunction', 'log_stream_name': u'ALL', 'watch': False, 'aws_region': u'eu-west-1', 'start': u'1d', 'aws_secret_access_key': 'SENSITIVE', 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/myfunction', 'ALL', '-s1d']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 125, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 237, in list_logs
    pool.join()
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 461, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 86, in wait
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 510, in switch
    return greenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x1087034b0 select default pending=0 ref=0 resolver=<gevent.resolver_thread.Resolver at 0x108835e50 pool=<ThreadPool at 0x108840e10 0/8/10>> threadpool=<ThreadPool at 0x108840e10 0/8/10>>)
================================================================================
```

**Comment by jorgebastida** [comment]
I've just pushed a new version (0.1.0) to pypi which should fix this issue.
https://pypi.python.org/pypi/awslogs/0.1.0
