### ISSUE TITLE
Exceiption while getting logs

### ISSUE THREAD

**Issue by yakupyuce** [jorgebastida/awslogs#164]
I got exception when I start awslogs get myswarm --start='16/11/2017 03:00' --end='16/11/2017 14:30'|grep myservice1

The error message is:
Version: 0.7.0
Python: 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
boto3 version: 1.4.1
Platform: Darwin-16.7.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': '16/11/2017 14:30', 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': 'ALL', 'watch': False, 'aws_region': None, 'aws_session_token': 'SENSITIVE', 'start': '16/11/2017 03:00', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'log_group_name': 'swarm-prod', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'swarm-prod', '--start=16/11/2017 03:00', '--end=16/11/2017 14:30']

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 136, in consumer
    for event in generator():
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 123, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/Library/Python/2.7/site-packages/botocore/parsers.py", line 211, in parse
    parsed = self._do_parse(response, shape)
  File "/Library/Python/2.7/site-packages/botocore/parsers.py", line 586, in _do_parse
    original_parsed = self._parse_body_as_json(response['body'])
  File "/Library/Python/2.7/site-packages/botocore/parsers.py", line 574, in _parse_body_as_json
    original_parsed = json.loads(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 800563 (char 800562)

**Comment by yakup** [comment]
Any comment?
