### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 242-245: character maps to <undefined>

### ISSUE THREAD

**Issue by camhart** [jorgebastida/awslogs#165]
```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
boto3 version: 1.4.7
Platform: Windows-10-10.0.16299
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': '2017-12-05T12:00:00', 'log_group_name': '/aws/lambda/asdf-prod-createAccount', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '2017-11-01T12:00:00', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['C:\\Python27\\Scripts\\awslogs', 'get', '/aws/lambda/asdf-prod-createAccount', '--start=2017-11-01T12:00:00', '--end=2017-12-05T12:00:00', '--profile', 'asdf-prod']

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 196, in list_logs
    consumer()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 185, in consumer
    print(' '.join(output))
  File "c:\python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "c:\python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 242-245: character maps to <undefined>
================================================================================
```

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
