### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd3' in position 341: ordinal not in range(128)

### ISSUE THREAD

**Issue by luis-rodriguez** [jorgebastida/awslogs#171]
```
Version: 0.10.0
Python: 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
boto3 version: 1.5.12
Platform: Darwin-16.7.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': '/some/log', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': True, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '/some/log', '--watch']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 185, in consumer
    print(' '.join(output))
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd3' in position 341: ordinal not in range(128)
```

**Comment by jorgebastida** [comment]
Will follow up here https://github.com/jorgebastida/awslogs/issues/215
