### ISSUE TITLE
NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by sedovalx** [jorgebastida/awslogs#178]
Here is how I called the awslogs:

```
$ awslogs get /aws/lambda/fus-frontend-proxy-handler-dev
```

I'm only starting to use it. So probably it is me who done something wrong but anyway

```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------

Version: 0.10.0
Python: 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
boto3 version: 1.5.29
Platform: Darwin-17.4.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': '/aws/lambda/fus-frontend-proxy-handler-dev', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/fus-frontend-proxy-handler-dev']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/usr/local/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 295, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 368, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
```

**Comment by james-ovens** [comment]
I am seeing the same thing, simply by doing the following after having installed:
awslogs groups

**Comment by james-ovens** [comment]
It appears there is no way to pass in the region as part of the command, but after looking in bin.py I can see it will pick up the region from the AWS_REGION environment variable.
So a work around for this is to do a
export AWS_REGION=<YOUR_REGION> 
before running the command.

**Comment by sedovalx** [comment]
The simple workaround form me is to pass `--aws-region=eu-west-1` in the command, it works. The only reason I posted the issue is this "You've found a bug!" thing. And anyway, it is not good to throw with a stacktrace if one of the required parameters is missing.

**Comment by jorgebastida** [comment]
We should handle this expection and return a helpful message. Going to follow up here https://github.com/jorgebastida/awslogs/issues/226

**Comment by tiwaris436** [comment]
Where is bin.py folder ?
