### ISSUE TITLE
issue listing groups

### ISSUE THREAD

**Issue by narsinallamilli** [jorgebastida/awslogs#181]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
boto3 version: 1.6.10
Platform: Darwin-17.4.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups']

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/Library/Python/2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Library/Python/2.7/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Library/Python/2.7/site-packages/botocore/args.py", line 79, in get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 289, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://logs.US East (N. Virginia).amazonaws.com
================================================================================

**Comment by xueshanf** [comment]
@narsinallamilli noticed `'aws_region': None,` in the trace.. curious how did you configure your aws profile and if you have default region.

**Comment by narsinallamilli** [comment]
@xueshanf You are correct, I have update aws config and it worked. can you please help me on how I can open a cloudwatch log in tail mode(running log)?

**Comment by xueshanf** [comment]
@narsinallamilli just add "ALL --watch" in the awslogs command like so:
```
$ awslogs get <group name>  ALL --watch --profile=<aws profile>
```

**Comment by jorgebastida** [comment]
It does look like (initially) you had ``US East (N. Virginia)`` as you configured region name... which is invalid. There is an open issue to make awslogs give users a helpful message when that happens (https://github.com/jorgebastida/awslogs/issues/240)
