### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by kccheung** [jorgebastida/awslogs#183]
Version: 0.10.0
Python: 3.5.3 (default, May 15 2017, 22:32:22)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
boto3 version: 1.6.3
Platform: Darwin-16.7.0-x86_64-i386-64bit
Config: {'output_ingestion_time_enabled': False, 'aws_profile': 'SENSITIVE', 'output_stream_enabled': True, 'log_group_name': 'PowerArena-Dev-lg', 'aws_access_key_id': 'SENSITIVE', 'start': '7d ago', 'output_group_enabled': True, 'aws_session_token': 'SENSITIVE', 'func': 'list_logs', 'query': None, 'output_timestamp_enabled': False, 'watch': False, 'color_enabled': True, 'filter_pattern': None, 'aws_region': None, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': 'powerarena_manage_powerarena-core.*'}
Args: ['/Users/david/.pyenv/versions/powerarena-core-3.5.3/bin/awslogs', 'get', 'PowerArena-Dev-lg', 'powerarena_manage_powerarena-core.*', '--start=7d ago']

Traceback (most recent call last):
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/awslogs/core.py", line 137, in consumer
    for event in generator():
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/awslogs/core.py", line 124, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 605, in send
    r.content
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/vendored/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/vendored/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/david/.pyenv/versions/3.5.3/envs/powerarena-core-3.5.3/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/Users/david/.pyenv/versions/3.5.3/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

is this a bug of awslogs?

**Comment by Aub-C** [comment]
I'm getting the same error after updating the awscli to 'aws-cli/1.15.4'.

**Comment by jorgebastida** [comment]
This looks like a connectivity issue
