### ISSUE TITLE
You've found a bug! Please, raise an issue attaching the following traceback

### ISSUE THREAD

**Issue by hammonba** [jorgebastida/awslogs#187]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0]
boto3 version: 1.6.12
Platform: Linux-4.13.0-39-generic-x86_64-with-Ubuntu-17.10-artful
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'cybersecurity-staging', 'log_stream_name': 'ALL', 'aws_region': 'eu-west-1', 'watch': True, 'aws_access_key_id': 'SENSITIVE', 'start': '0m', 'aws_profile': 'SENSITIVE', 'filter_pattern': '{$.MESSAGE = ":kermit.cybersecurity.scanners.sentry-bay/perform-request"}', 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/home/ben/.local/bin/awslogs', 'get', 'cybersecurity-staging', '--aws-region', 'eu-west-1', '--profile', 'kermit', '-w', '--start=0m', '--filter', '{$.MESSAGE = ":kermit.cybersecurity.scanners.sentry-bay/perform-request"}']

Traceback (most recent call last):
  File "/home/ben/.local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/home/ben/.local/lib/python2.7/site-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/home/ben/.local/lib/python2.7/site-packages/awslogs/core.py", line 137, in consumer
    for event in generator():
  File "/home/ben/.local/lib/python2.7/site-packages/awslogs/core.py", line 124, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/ben/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
error: [Errno 104] Connection reset by peer
================================================================================

**Comment by blueyed** [comment]
Please format the issue, i.e. use ``` around the traceback.

**Comment by jorgebastida** [comment]
Looks like a connectivity issue
