### ISSUE TITLE
bug found

### ISSUE THREAD

**Issue by sukovanej** [jorgebastida/awslogs#188]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 3.6.5 (default, Apr  6 2018, 10:51:56)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
boto3 version: 1.7.14
Platform: Darwin-17.5.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/aws/lambda/my_lambda', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': True, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}
Args: ['/Users/suk/.pyenv/versions/my_lambda/bin/awslogs', 'get', '/aws/lambda/my_lambda', 'ALL', '--watch', '--profile', 'dev']

Traceback (most recent call last):
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/boto3/__init__.py", line 72, in _get_default_session
    setup_default_session()
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/boto3/__init__.py", line 34, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 726, in get_component
    return self._components.get_component(name)
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 922, in get_component
    self._components[name] = factory()
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 184, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/Users/suk/.pyenv/versions/3.6.5/envs/my_lambda/lib/python3.6/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (dev) could not be found
================================================================================

**Comment by jorgebastida** [comment]
It looks like you are calling awslogs with --profile=dev, but that profile is not correctly configured in your system. Here you can find the relevant documentation (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html).
