### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 319:

### ISSUE THREAD

**Issue by squinker** [jorgebastida/awslogs#19]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 213, in _raw_events_queue_consumer
    self.events_queue.put("{0}\n".format(' '.join(output)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 319: ordinal not in range(128)
<Greenlet at 0x7f3344135050: <bound method AWSLogs._raw_events_queue_consumer of <awslogs.core.AWSLogs object at 0x7f33441a1790>>> failed with UnicodeEncodeError

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.0.2
Python: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
boto version: 2.38.0
Platform: Linux-3.13.0-65-generic-x86_64-with-Ubuntu-14.04-trusty
Config: {'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': u'ALL', 'aws_region': u'eu-west-1', 'watch': False, 'start': u'1 days', 'log_group_name': u'bespin-prod', 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'bespin-prod', '--start=1 days']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 121, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 236, in list_logs
    pool.join()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 100, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
================================================================================

**Comment by jorgebastida** [comment]
Updating to the latest version ``0.1`` https://pypi.python.org/pypi/awslogs should fix this issue.

**Comment by saba0815** [comment]
Hi, i also get the above errors but without the verbosity (versions, config etc.) to file a new bug. awslogs version is 0.1.2. Do i have to activate it somehow?

**Comment by jorgebastida** [comment]
Could you please share the new traceback?

**Comment by saba0815** [comment]
This is an example:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 110, in consumer
    print(' '.join(output))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 241-242: ordinal not in range(128)
```

**Comment by saba0815** [comment]
Hi, did this help somehow?

**Comment by saba0815** [comment]
@jorgebastida , could the problem be on cloudwatch logs side being configured wrong regarding unicode?
