### ISSUE TITLE
You've found a bug! Please, raise an issue attaching the following traceback

### ISSUE THREAD

**Issue by cnpeyt** [jorgebastida/awslogs#201]
``` 
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.15 (default, May  1 2018, 16:44:37)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
boto3 version: 1.7.17
Platform: Darwin-17.5.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/cnpeyt/Library/Python/2.7/lib/python/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
================================================================================
```

**Comment by jorgebastida** [comment]
It looks like you didn't specify a region. The patch for https://github.com/jorgebastida/awslogs/issues/226 should fix this issue
