### ISSUE TITLE
Bug in awslogs

### ISSUE THREAD

**Issue by lakhanarya** [jorgebastida/awslogs#204]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.10 (default, Apr 26 2018, 12:43:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
boto3 version: 1.7.39
Platform: Darwin-16.7.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': '22/6/2018 00:00', 'log_group_name': '/aws/lambda/ResourceChangeListener', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '21/6/2018 00:00', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/Users/lakhanm/.pyenv/versions/2.7.10/bin/awslogs', 'get', '/aws/lambda/ResourceChangeListener', '--start=21/6/2018 00:00', '--end=22/6/2018 00:00']

Traceback (most recent call last):
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/awslogs/core.py", line 137, in consumer
    for event in generator():
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/awslogs/core.py", line 124, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/lakhanm/.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
error: [Errno 54] Connection reset by peer
================================================================================

**Comment by jorgebastida** [comment]
Looks like a connectivity issue
