### ISSUE TITLE
ResourceNotFoundException for seemingly every get call?

### ISSUE THREAD

**Issue by iDVB** [jorgebastida/awslogs#209]
```
Traceback (most recent call last):
  File "/usr/local/bin/awslogs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 76, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 69, in _get_streams_from_pattern
    for stream in self.get_streams(group):
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 228, in get_streams
    for page in paginator.paginate(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

I get this same error no matter what logs I seem to call. 

On:
macOS 10.13.6
pip 10.0.1
Python 2.7.15

**Comment by jorgebastida** [comment]
Might it be permission related? Is this still a issue?

**Comment by meetupwayne** [comment]
I am also seeing this issue, same error.

I don't think it is a permissions issue because I am able to use the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-logs.html) to get logs from the same log group using the same set of credentials.

**Comment by oakgary** [comment]
anyone found a solution to this?

just installed the tool, all i did so far was this:
`$ brew install awslogs` ✅
`$ awslogs groups` ✅
`$ awslogs streams GROUP` ❌
```
Traceback (most recent call last):
  File "/usr/local/bin/awslogs", line 33, in <module>
    sys.exit(load_entry_point('awslogs==0.14.0', 'console_scripts', 'awslogs')())
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/awslogs/bin.py", line 179, in main
    getattr(logs, options.func)()
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/awslogs/core.py", line 241, in list_streams
    for stream in self.get_streams():
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/awslogs/core.py", line 261, in get_streams
    for page in paginator.paginate(**kwargs):
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awslogs/0.14.0_1/libexec/lib/python3.9/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

looks like every get and streams command throws this error
