### ISSUE TITLE
You've found a bug! Please, raise an issue attaching the following traceback https://github.com/jorgebastida/awslogs/issues/new

### ISSUE THREAD

**Issue by baskicisamet** [jorgebastida/awslogs#212]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
boto3 version: 1.7.48
Platform: Darwin-17.5.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': 'eu-west-1', 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups', '--aws-region', 'eu-west-1', '--profile', 'reis']

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 203, in list_groups
    for group in self.get_groups():
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 217, in get_groups
    for page in paginator.paginate(**kwargs):
  File "/Library/Python/2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Library/Python/2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 173, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 157, in create_request
    operation_name=operation_model.name)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Library/Python/2.7/site-packages/botocore/signers.py", line 156, in sign
    auth.add_auth(request)
  File "/Library/Python/2.7/site-packages/botocore/auth.py", line 352, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials

**Comment by jorgebastida** [comment]
Duplicate https://github.com/jorgebastida/awslogs/issues/236
