### ISSUE TITLE
Specifying asterisk as query causes error

### ISSUE THREAD

**Issue by PicoSushi** [jorgebastida/awslogs#217]
I ran `awslogs get MY_STREAM_NAME '*'` and error as below:

Version: 0.10.0
Python: 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531]
boto3 version: 1.9.10
Platform: Linux-4.14.70-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': 'MY_STREAM_NAME', 'log_stream_name': '*', 'filter_pattern': None, 'watch': False, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}
Args: ['/home/picosushi/.local/bin/awslogs', 'get', 'MY_STREAM_NAME', '*']

Traceback (most recent call last):
  File "/home/picosushi/.local/lib/python3.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/home/picosushi/.local/lib/python3.7/site-packages/awslogs/core.py", line 76, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/home/picosushi/.local/lib/python3.7/site-packages/awslogs/core.py", line 68, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 1

**Comment by theKashyap** [comment]
def _get_streams_from_pattern(self, group, pattern):
        """Returns streams in ``group`` matching ``pattern``."""
        pattern = '.*' if pattern == self.ALL_WILDCARD else pattern
        reg = re.compile('^{0}'.format(pattern))
        for stream in self.get_streams(group):
            if re.match(reg, stream):
                yield stream

Relevant code from [core.py](https://github.com/jorgebastida/awslogs/blob/master/awslogs/core.py#L94).

1. Is `*` a valid python regex? It's more a shell glob expression than python regex.
2. `'^{0}'.format(pattern)` is kinda changing what user provided. It's making it _"starting with `pattern`"_ than _"matching `pattern`"_



Possible solutions:
1. If being backwards compatible is mandatory: Update README to say use special keyword `ALL` if you want all streams instead of `*`.
2. If being backwards compatible is not needed here:
2.1 change reg = `re.compile('^{0}'.format(pattern))` to `reg = re.compile('{0}'.format(pattern))`
2.2 enhance arg parsing logic as Code0x58 suggested: 

> "it can be guarded against in the argparse config by making a function for the pattern type which can sanitise and compile the pattern"

**Comment by jorgebastida** [comment]
Thank you very much for the triage work!
- We should remove ``^``,  that was a bad idea.
- We should update the documentation to make clear this parameter has to be a valid python regexp
- As @Code0x58 mentioned... it would be amazing if we could pre-compile the regexp so we could notify the user if the expression is not valid.
- I am +1 to keep ALL as a valid wild card as using ``*`` in the terminal tend to be a pita as it replaces it with all the files in the current directory.

@theKashyap would you volunteer to send a PR?

**Comment by theKashyap** [comment]
@jorgebastida PR created:  fix for issue/217-Specifying-asterisk-as-query-causes-error
Not sure on versioning so haven't updated that.
Added a few loggers, not sure if you want to leave them in or not.
