### ISSUE TITLE
Bug with reg expression starting on *

### ISSUE THREAD

**Issue by jorsermar** [jorgebastida/awslogs#220]
```
Version: 0.10.0
Python: 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
boto3 version: 1.4.4
Platform: Darwin-17.4.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': False, 'end': None, 'log_group_name': '/services/production/affjet', 'log_stream_name': '*-web-*', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': False}
Args: ['/usr/local/bin/awslogs', 'get', '/services/production/affjet', '*-web-*', '--no-group', '--no-stream']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.10/libexec/lib/python2.7/site-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/Cellar/awslogs/0.10/libexec/lib/python2.7/site-packages/awslogs/core.py", line 76, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/usr/local/Cellar/awslogs/0.10/libexec/lib/python2.7/site-packages/awslogs/core.py", line 68, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/usr/local/Cellar/awslogs/0.10/libexec/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/awslogs/0.10/libexec/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: nothing to repeat

```

**Comment by cykl** [comment]
Hi @jorsermar,

`*-web-*` isn't a valid regexp, try `.*-web-.*`.
