### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by gfloure** [jorgebastida/awslogs#221]
```
> 
>  Version: 0.10.0
> Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
> [Clang 6.0 (clang-600.0.57)]
> boto3 version: 1.9.28
> Platform: Darwin-18.0.0-x86_64-i386-64bit
> Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_prefix': None, 'func': 'list_groups'}
> Args: ['/Library/Frameworks/Python.framework/Versions/3.7/bin/awslogs', 'groups']
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 56, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/httpsession.py", line 258, in send
>     decode_content=False,
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 343, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
>     raise value
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
>     self._validate_conn(conn)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
>     conn.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
>     conn = self._new_conn()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x10de85a20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/awslogs/bin.py", line 172, in main
>     getattr(logs, options.func)()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/awslogs/core.py", line 203, in list_groups
>     for group in self.get_groups():
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/awslogs/core.py", line 217, in get_groups
>     for page in paginator.paginate(**kwargs):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
>     response = self._make_request(current_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
>     return self._method(**current_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 610, in _make_api_call
>     operation_model, request_dict)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
>     return self._send_request(request_dict, operation_model)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/endpoint.py", line 136, in _send_request
>     success_response, exception):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
>     caught_exception=caught_exception, request_dict=request_dict)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
>     if self._checker(attempts, response, caught_exception):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
>     caught_exception)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
>     return self._checker(attempt_number, response, caught_exception)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
>     caught_exception)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
>     attempt_number, caught_exception)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
>     raise caught_exception
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/endpoint.py", line 179, in _get_response
>     http_response = self._send(request)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/endpoint.py", line 223, in _send
>     return self.http_session.send(request)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/httpsession.py", line 278, in send
>     raise EndpointConnectionError(endpoint_url=request.url, error=e)
> botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.u-west-3.amazonaws.com/"
> ================================================================================
> 
> 
```

**Comment by jorgebastida** [comment]
Looks like a connectivity issue in your end
