### ISSUE TITLE
botocore.exceptions.RefreshWithMFAUnsupportedError: Cannot refresh credentials: MFA token required.

### ISSUE THREAD

**Issue by gms8994** [jorgebastida/awslogs#232]
```Version: 0.11.0
Python: 3.7.2 (default, Dec 27 2018, 07:35:06) 
[Clang 10.0.0 (clang-1000.11.45.5)]
boto3 version: 1.9.62
Platform: Darwin-18.2.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '<redacted>', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', '<redacted>', '-w', '--profile', '<redacted>', '--no-color']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 178, in main
    getattr(logs, options.func)()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 223, in list_logs
    consumer()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 164, in consumer
    for event in generator():
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 151, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/signers.py", line 149, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/signers.py", line 229, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 518, in get_frozen_credentials
    self._refresh()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 413, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 429, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 175, in __call__
    raise RefreshWithMFAUnsupportedError()
botocore.exceptions.RefreshWithMFAUnsupportedError: Cannot refresh credentials: MFA token required.

```

**Comment by jorgebastida** [comment]
It would be nice if ``awslogs`` could handle this exception and give the user a useful message.
This is a nice issue for new contributors.
