### ISSUE TITLE
Trying to tail a log

### ISSUE THREAD

**Issue by john-mcdonnell** [jorgebastida/awslogs#233]
This is the first time I have used this utility so I may be trying to do something in the wrong way. Her is the log output:
```Version: 0.11.0
Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
boto3 version: 1.9.78
Platform: Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
Config: {'output_timestamp_enabled': False, 'watch_interval': 1, 'end': None, 'log_group_name': 'sentiment-engine--b3672ac8bc8b', 'log_stream_name': '*INFO*', 'output_group_enabled': True, 'color': 'auto', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '1d', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'sentiment-engine--b3672ac8bc8b', '*INFO*', '-s1d']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 178, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 103, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 95, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: nothing to repeat

```

**Comment by cykl** [comment]
`STREAM_EXPRESSION` must be a regex but `*INFO*` is not. Try `.*INFO.*`.

**Comment by jorgebastida** [comment]
@cykl is right! - Closing
