### ISSUE TITLE
JSONFileCache error

### ISSUE THREAD

**Issue by Ismael** [jorgebastida/awslogs#234]
```Version: 0.11.0
Python: 2.7.14 (default, Jul 26 2018, 19:59:38) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
boto3 version: 1.4.4
Platform: Linux-4.14.77-81.59.amzn2.x86_64-x86_64-with-glibc2.2.5
Config: {'func': 'list_groups', 'aws_region': 'us-east1', 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/bin/awslogs', 'groups', '--aws-region', 'us-east-1']

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 89, in __init__
    self.aws_region
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 40, in boto3_client
    credential_provider.cache = botocore.credentials.JSONFileCache(cache_dir)
AttributeError: 'module' object has no attribute 'JSONFileCache'


This is probably due that it required botocore 1.5.95
Installing latest botocore fixed this.

**Comment by wahabmk** [comment]
I also faced this issue, so I looked through the Releases for botocore. I found that the class 'botocore.credentials.JSONFileCache' was added since version 1.8.14. I've created a pull request (#241) to add 'botocore>=1.8.14' as a dependency to setup.py

**Comment by craigbarrau** [comment]
Thanks for posting that hint @wahabmk 
Resolved as soon as I did `pip install -U botocore`

**Comment by jorgebastida** [comment]
We'll fix this bug as part of https://github.com/jorgebastida/awslogs/pull/241
