### ISSUE TITLE
Bug 0.10.0 

### ISSUE THREAD

**Issue by hgsgtk** [jorgebastida/awslogs#237]
```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 3.7.1 (default, Nov 28 2018, 11:51:47) 
[Clang 10.0.0 (clang-1000.11.45.5)]
boto3 version: 1.4.4
Platform: Darwin-18.2.0-x86_64-i386-64bit

Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/ecs/**my-group-name**', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': True, 'output_group_enabled': False, 'output_stream_enabled': False, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}

Args: ['/usr/local/bin/awslogs', 'get', '-w', '-G', '-S', '/ecs/**my-group-name**']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 172, in main getattr(logs, options.func)()
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/core.py", line 137, in consumer
    for event in generator():
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/core.py", line 124, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 531, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__caught_exception)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__caught_exception)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__attempt_number, caught_exception)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.ap-northeast-1.amazonaws.com/"
================================================================================

**Comment by jorgebastida** [comment]
This looks to me like a connectivity issue. Can you reproduce it?

**Comment by hgsgtk** [comment]
Not since then. I have no idea to reproduce it, so there may be no problem.
