### ISSUE TITLE
You've found a bug! Please, raise an issue attaching the following traceback

### ISSUE THREAD

**Issue by froehr** [jorgebastida/awslogs#238]
```Version: 0.11.0
Python: 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
boto3 version: 1.4.4
Platform: Darwin-18.2.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'watch_interval': 1, 'end': None, 'log_group_name': 'ecs/e-power-customer', 'log_stream_name': 'ALL', 'output_group_enabled': True, 'color': 'auto', 'aws_region': None, 'watch': True, 'aws_access_key_id': 'SENSITIVE', 'start': '1m ago', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'output_stream_enabled': False}
Args: ['/usr/local/bin/awslogs', 'get', '--start=1m ago', '--watch', 'ecs/e-power-customer', '-S']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 89, in __init__
    self.aws_region
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 40, in boto3_client
    credential_provider.cache = botocore.credentials.JSONFileCache(cache_dir)
AttributeError: 'module' object has no attribute 'JSONFileCache'

```

**Comment by jorgebastida** [comment]
We are dealing with this issue here https://github.com/jorgebastida/awslogs/pull/241
