### ISSUE TITLE
Got an error while getting logs

### ISSUE THREAD

**Issue by nervebassmaster** [jorgebastida/awslogs#239]
```Version: 0.11.0
Python: 3.7.1 (default, Nov 28 2018, 11:51:47)
[Clang 10.0.0 (clang-1000.11.45.5)]
boto3 version: 1.9.62
Platform: Darwin-18.2.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': 'SENSITIVE', 'log_stream_name': 'ALL', 'filter_pattern': 'success', 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '2019-02-06T00:00:00', 'end': '2019-02-09T23:59:59', 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', 'SENSITIVE', '-s', '2019-02-06T00:00:00', '-e', '2019-02-09T23:59:59', '--filter-pattern', 'success', '--output', 'text']
```
```
Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 178, in main
    getattr(logs, options.func)()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 223, in list_logs
    consumer()
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 212, in consumer
    print(' '.join(output))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jorgebastida** [comment]
We already tried to fix this issue (https://github.com/jorgebastida/awslogs/pull/128) but apparently we did't managed to handle all situations.

Can you consistently reproduce this issue?
