### ISSUE TITLE
Handle invalid region configurations

### ISSUE THREAD

**Issue by baltameme** [jorgebastida/awslogs#240]
```Version: 0.11.0
Python: 2.7.15 (default, Oct  2 2018, 11:42:04) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
boto3 version: 1.9.96
Platform: Darwin-18.2.0-x86_64-i386-64bit
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 178, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 230, in list_groups
    for group in self.get_groups():
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 244, in get_groups
    for page in paginator.paginate(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.Frankfurt.amazonaws.com/"

**Comment by jorgebastida** [comment]
It looks like your region configuration is set to ``Frankfurt`` (probably in your env?) and that is not a valid AWS region. The correct name for the Frankfurt region is ``eu-central-1``.

**Comment by jorgebastida** [comment]
It would be nice if ``awslogs`` tried to determine if the provided region is a valid one before using it.

- Check if boto3 has an api to list regions, otherwise hardcode them
- Validate region using the list of valid regions.
- If trying to use a region not in the list warning about the possible error, but do not fail so we don't need to urgently update ``awslogs`` every time aws releases a region.

This is a nice ticket for new contributors

**Comment by markuman** [comment]
```
>>> boto3.session.Session().get_available_regions('logs')
['ap-northeast-1', 'ap-northeast-2', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-north-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'sa-east-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
```

However, it is not a complete list. 16 vs 21

https://docs.aws.amazon.com/general/latest/gr/rande.html#cwl_region

**Comment by markuman** [comment]
Should the warning use `sys.stdout` or introduce `import logging` with log levels?  
And is the boto3_client function the right place (after line 42) to place this? https://github.com/jorgebastida/awslogs/blob/master/awslogs/core.py#L34
@jorgebastida
