### ISSUE TITLE
Bug trying to run awslogs

### ISSUE THREAD

**Issue by birmsi** [jorgebastida/awslogs#242]
Found a bug when trying to run the awslogs.
Follows the traceback:

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

```Version: 0.11.0
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
boto3 version: 1.9.110
Platform: Windows-10-10.0.14393-SP0
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': 'eu-west-1', 'log_group_name': 'path/streaming', 'log_stream_name': 'ALL', 'filter_pattern': '{ $.Level=Error }', 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': "'5m'", 'end': None, 'color': 'auto', 'query': 'RenderedMessage', 'func': 'list_logs'}
Args: ['C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\awslogs', 'get', 'path/streaming', '--profile', 'prod', '--aws-region', 'eu-west-1', "--start='5m'", '--filter-pattern={ $.Level=Error }', '--query=RenderedMessage', '--watch']

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\awslogs\bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\awslogs\core.py", line 89, in __init__
    self.aws_region
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\awslogs\core.py", line 38, in boto3_client
    credential_provider = core_session.get_component('credential_provider').get_provider('assume-role')
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\session.py", line 679, in get_component
    return self._components.get_component(name)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\session.py", line 902, in get_component
    self._components[name] = factory()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\session.py", line 145, in <lambda>
    lambda:  botocore.credentials.create_credential_resolver(self))
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\credentials.py", line 62, in create_credential_resolver
    metadata_timeout = session.get_config_variable('metadata_service_timeout')
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\session.py", line 233, in get_config_variable
    logical_name)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\configprovider.py", line 226, in get_config_variable
    return provider.provide()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\configprovider.py", line 323, in provide
    value = provider.provide()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\configprovider.py", line 382, in provide
    config = self._session.get_scoped_config()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\botocore\session.py", line 334, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (prod) could not be found

```

**Comment by jorgebastida** [comment]
It looks like you are calling ``awslogs`` with ``--profile=prod``, but that profile is not correctly configured in your system. Here you can find the relevant documentation (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html).

**Comment by jorgebastida** [comment]
Closing as this is not an awslogs bug
