### ISSUE TITLE
FilterLogEvents operation: 1 validation error detected: Value 'C:/Program Files/Git/aws/lambda/my-lambda' at 'logGroupName' failed to satisfy constraint

### ISSUE THREAD

**Issue by davegallant** [jorgebastida/awslogs#245]
**Environment:** Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

Unable to retrieve logs due to a PATH issue?

```bash
$ awslogs get /aws/lambda/my-lambda ALL --query=Billed
Traceback (most recent call last):
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\daveg\AppData\Local\Programs\Python\Python37\Scripts\awslogs.exe\__main__.py", line 9, in <module>
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\awslogs\bin.py", line 178, in main
    getattr(logs, options.func)()
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\awslogs\core.py", line 223, in list_logs
    consumer()
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\awslogs\core.py", line 164, in consumer
    for event in generator():
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\awslogs\core.py", line 151, in generator
    response = self.client.filter_log_events(**kwargs)
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\users\daveg\appdata\local\programs\python\python37\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the FilterLogEvents operation: 1 validation error detected: Value 'C:/Program Files/Git/aws/lambda/my-lambda' at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+
```

**Comment by neilodonuts** [comment]
This happens in git-bash running the utility as well. It seems to be trying to translate what it _thinks_ to be paths into Windows paths. For example, passing in `/aws/lambda/example` gets translated (on my git-bash system) to `C:/Program Files/Git/aws/lambda/example`.

**Comment by jorgebastida** [comment]
Yes, this seems similar to what bash does when you pass ``*``. Have you tried to do something like... ``awslogs get "/aws/lambda/my-lambda" ALL --query=Billed``

**Comment by jorgebastida** [comment]
Closing as this is not an awslogs bug.

**Comment by DeMcA** [comment]
For anyone coming across this ticket when searching, solutions include something like:
`MSYS2_ARG_CONV_EXCL=\* awslogs get /aws/lambda/my-lambda-name ALL -s1d`

and somewhat counterintuitively:
`awslogs get "//aws\lambda\my-lambda-name ALL -s1d`

See documentation here: http://www.mingw.org/wiki/Posix_path_conversion
