### ISSUE TITLE
Exception while getting logs with "." in the query string

### ISSUE THREAD

**Issue by omriceisler** [jorgebastida/awslogs#246]
was trying to use the query string with to filter a field name with . in it. 
i believe this is causing an issue.

Pasting the logs as asked (removed the service's name):

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

```Version: 0.11.0
Python: 2.7.15 (default, Oct  2 2018, 11:47:18)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
boto3 version: 1.9.130
Platform: Darwin-18.2.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'watch_interval': 1, 'end': None, 'log_group_name': 'XXXXXXXXXXXXXX', 'log_stream_name': 'ALL', 'output_group_enabled': True, 'color': 'auto', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '1d', 'aws_profile': 'SENSITIVE', 'filter_pattern': 'REJECTED_BY', 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': 'grpc.response.content', 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'NAMEOFSERVICE', '--start=1d', '--filter-pattern=REJECTED_BY', '--query=grpc.response.content']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 178, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 223, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 206, in consumer
    parsed = json.loads(event['message'])
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 248819 (char 248818)

**Comment by omriceisler** [comment]
Actually this may be due to the --start tag. as when i changed it, the exception stopped happening

**Comment by jorgebastida** [comment]
The issue is that awslogs couldn't parse your log message as a valid json in order to apply your filtering. 

We should update the code to correctly try/except these cases, and show a useful message (https://github.com/jorgebastida/awslogs/blob/master/awslogs/core.py#L206)

This is a good easy ticket for new contributors.

**Comment by omriceisler** [comment]
Hi, Thanks!

Do you think the script should exit upon this exception, or simply output an error message instead of the log JSON (along with the group and stream name) ?
