### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by anand-s** [jorgebastida/awslogs#255]
```Version: 0.11.0
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
boto3 version: 1.5.36
Platform: Windows-10-10.0.17134
Config: {'output_timestamp_enabled': False, 'watch_interval': 1, 'end': None, 'log_group_name': 'dtna-pm-test-19-1-us-east-1', 'log_stream_name': 'ALL', 'output_group_enabled': True, 'color': 'auto', 'aws_region': 'us-east-1', 'watch': True, 'aws_access_key_id': 'SENSITIVE', 'start': "'30s", 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'output_stream_enabled': True}
Args: ['C:\\Python27\\Scripts\\awslogs', 'get', 'dtna-pm-test-19-1-us-east-1', '-aws-region', 'us-east-1', "--start='30s", "ago'", '--watch']

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\awslogs\bin.py", line 178, in main
    getattr(logs, options.func)()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 223, in list_logs
    consumer()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 212, in consumer
    print(' '.join(output))
  File "c:\python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "c:\python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03bc' in position 382: character maps to <undefined>

```

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
