### ISSUE TITLE
NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by enrique-marin-clip** [jorgebastida/awslogs#268]
```Version: 0.11.0
Python: 2.7.12 (default, Aug 22 2019, 16:36:40) 
[GCC 5.4.0 20160609]
boto3 version: 1.6.8
Platform: Linux-4.4.0-157-generic-x86_64-with-Ubuntu-16.04-xenial
Config: {'func': 'list_groups', 'aws_region': None, 'log_group_prefix': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE'}
Args: ['/usr/local/bin/awslogs', 'groups', 'oregon']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 89, in __init__
    self.aws_region
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 48, in boto3_client
    region_name=aws_region)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.

**Comment by emilbryggare** [comment]
Same for me. Does not seem to respect my ~/.aws/config file. 
Solved it with setting an environment variable instead:
`export AWS_REGION=us-east-1`

**Comment by Juftin** [comment]
You can also pass flag `--aws-region=us-east-1`
