### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character on Windows

### ISSUE THREAD

**Issue by agrandillo** [jorgebastida/awslogs#273]
Here is the stack trace for the following command: 
awslogs get 'pathToMyGroup' ALL --aws-region='anyRegion' --start='1 min' > out
==>
```Version: 0.11.0
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
boto3 version: 1.9.236
Platform: Windows-10-10.0.18362-SP0
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': 'us-west-2', 'log_group_name': '/aws/lambda/api-builder', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '1 min', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['C:\\Users\\Anthony\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\awslogs', 'get', '/aws/lambda/api-builder', 'ALL', '--aws-region=us-west-2', '--start=1 min']

Traceback (most recent call last):
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\site-packages\awslogs\bin.py", line 178, in main
    getattr(logs, options.func)()
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\site-packages\awslogs\core.py", line 223, in list_logs
    consumer()
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\site-packages\awslogs\core.py", line 212, in consumer
    print(' '.join(output))
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f9d4' in position 1410: character maps to <undefined>

```

**Comment by monnetchr** [comment]
`UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 490: character maps to <undefined>`
Same stacktrace.

**Comment by monnetchr** [comment]
Workaround: using WSL I could get the log. It contains such characters:
`Log Contents:
�r�[�=�T��fj\d
���f�z��n�i䂕�u_�c=��1s�l[���yR��e�q�&p7�a0�"U���-�/��~ѐ$2O{a_�aޅ|$$�{���`

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
