### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region

### ISSUE THREAD

**Issue by irynasuprun** [jorgebastida/awslogs#288]
```Version: 0.11.0
Python: 3.7.3 (default, Apr 17 2019, 11:23:23)
[Clang 10.0.1 (clang-1001.0.46.3)]
boto3 version: 1.11.14
Platform: Darwin-19.3.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': 'ECSLogGroup-proton-gateway', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '20m ago', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', 'ECSLogGroup-proton-gateway', '--start=20m ago', '--watch']

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python3.7/site-packages/awslogs/core.py", line 89, in __init__
    self.aws_region
  File "/usr/local/lib/python3.7/site-packages/awslogs/core.py", line 48, in boto3_client
    region_name=aws_region)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/client.py", line 83, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/client.py", line 247, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/args.py", line 217, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/args.py", line 300, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/client.py", line 321, in resolve
    service_name, region_name)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/isuprun/Library/Python/3.7/lib/python/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by WhyNotHugo** [comment]
Keep getting the same error. It's super annoying, since I've already configured awscli to use the right region, so it's pretty unhandy to type it every single time.

**Comment by WhyNotHugo** [comment]
After like 30 minutes, I managed to figure out how to run this:
```bash
awslogs groups --aws-region=us-west-2 get --profile=idf groups
```

Note that the order of all the options is really important. I thing the real issue here is the lack of a simple usage summary, in the usual format:

```console
$ vdirsyncer --help
Usage: vdirsyncer [OPTIONS] COMMAND [ARGS]...

  Synchronize calendars and contacts

Options:
  -v, --verbosity LVL  Either CRITICAL, ERROR, WARNING, INFO or DEBUG
  --version            Show the version and exit.
  -c, --config FILE    Config file to use.
  --help               Show this message and exit.

Commands:
  discover  Refresh collection cache for the given pairs.
  metasync  Synchronize metadata of the given collections or pairs.
  repair    Repair a given collection.
  sync      Synchronize the given collections or pairs.
$ vdirsyncer discover help
```

I know `click` can auto-do this for you, but I've no idea on `argparse`.

`--region` and `--profile` make a lot more sense as the sort of options that go at the beggining, not at the end, since they apply to all commands, rather than being command-specific.

**Comment by WhyNotHugo** [comment]
Also, it seems you always need to specify `--profile=blah`; `--profile blah` won't work, oddly.
