### ISSUE TITLE
Bug while trying to pull logs.

### ISSUE THREAD

**Issue by Erniedb** [jorgebastida/awslogs#289]
```Version: 0.11.0
Python: 3.8.1 (default, Dec 27 2019, 18:06:00)
[Clang 11.0.0 (clang-1100.0.33.16)]
boto3 version: 1.9.62
Platform: macOS-10.15.3-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': 'default', 'log_stream_name': 'wh-api', 'filter_pattern': 'Relayed to url', 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '10 days ago', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', 'default', 'wh-api', '--start=10 days ago', '--filter', 'Relayed to url', '--profile', 'logs']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/awslogs/core.py", line 84, in __init__
    self.client = boto3_client(
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/awslogs/core.py", line 38, in boto3_client
    credential_provider = core_session.get_component('credential_provider').get_provider('assume-role')
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/session.py", line 653, in get_component
    return self._components.get_component(name)
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/session.py", line 870, in get_component
    self._components[name] = factory()
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/session.py", line 140, in <lambda>
    lambda:  botocore.credentials.create_credential_resolver(self))
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/credentials.py", line 62, in create_credential_resolver
    metadata_timeout = session.get_config_variable('metadata_service_timeout')
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/session.py", line 206, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 213, in get_config_variable
    return provider.provide()
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 310, in provide
    value = provider.provide()
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/configprovider.py", line 369, in provide
    config = self._session.get_scoped_config()
  File "/usr/local/Cellar/awslogs/0.11.0_1/libexec/lib/python3.8/site-packages/botocore/session.py", line 308, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (logs) could not be found

```

**Comment by gene1wood** [comment]
Do you have a profile configured in `~/.aws/config` called `logs`? What does your `~/.aws/config` contain?
