### ISSUE TITLE
Bug on awslogs

### ISSUE THREAD

**Issue by arturi-to** [jorgebastida/awslogs#293]
Hi,

When I run log_group=$(awslogs groups -p ecsworkshop-frontend), from the ecsworkshop guide I receive the following error

```Version: 0.11.0
Python: 3.6.10 (default, Feb 10 2020, 19:55:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
boto3 version: 1.12.16
Platform: Linux-4.14.165-103.209.amzn1.x86_64-x86_64-with-glibc2.3.4
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': '', 'log_group_prefix': 'ecsworkshop-frontend', 'func': 'list_groups'}
Args: ['/home/ec2-user/environment/.env/bin/awslogs', 'groups', '-p', 'ecsworkshop-frontend']

Traceback (most recent call last):
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/awslogs/core.py", line 89, in __init__
    self.aws_region
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/awslogs/core.py", line 48, in boto3_client
    region_name=aws_region)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/botocore/client.py", line 85, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/botocore/client.py", line 287, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/botocore/args.py", line 107, in get_client_args
    client_cert=new_config.client_cert)
  File "/home/ec2-user/environment/.env/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 261, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://logs..amazonaws.com

I think is the extra dot in the endpoint

**Comment by olivierguzzi** [comment]
See the other issue you opened, the endpoint format is 
"https://logs." + region + ".amazonaws.com"
