### ISSUE TITLE
Access Denied Exception should show be a handled error

### ISSUE THREAD

**Issue by facundofarias** [jorgebastida/awslogs#3]
Currently is showing:
--------------------------------------------------------------------------------
Version: 0.0.1
Python: 2.7.5 (default, Mar  9 2014, 22:15:05)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
boto version: 2.38.0
Platform: Darwin-13.4.0-x86_64-i386-64bit
Config: {'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'XXXX', 'log_stream_name': u'ALL', 'watch': False, 'aws_region': u'eu-west-1', 'start': u'2w ago', 'log_group_name': u'XXXX', 'func': 'list_logs', 'aws_access_key_id': 'XXXX', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'XXXX', '--start=2w ago']

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/awslogs/bin.py", line 116, in main
    getattr(logs, options.func)()
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 213, in list_logs
    self.register_publishers()
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 228, in register_publishers
    for group, stream in self._get_streams_from_patterns(self.log_group_name, self.log_stream_name):
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 89, in _get_streams_from_patterns
    for group in self._get_groups_from_pattern(log_group_pattern):
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 98, in _get_groups_from_pattern
    for group in self.get_groups():
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 257, in get_groups
    response = self.connection.describe_log_groups(next_token=next_token)
  File "/Library/Python/2.7/site-packages/awslogs/core.py", line 39, in aws_connection_wrap
    return getattr(self.connection, name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto/logs/layer1.py", line 268, in describe_log_groups
    body=json.dumps(params))
  File "/Library/Python/2.7/site-packages/boto/logs/layer1.py", line 576, in make_request
    body=json_body)
JSONResponseError: JSONResponseError: 400 Bad Request
{u'Message': u'User: XXXX is not authorized to perform: logs:DescribeLogGroups on resource: XXXX', u'__type': u'AccessDeniedException'}

**Comment by jorgebastida** [comment]
This should be fixed now on master. Thanks!
