### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\x9d' in position 204

### ISSUE THREAD

**Issue by haywiremk** [jorgebastida/awslogs#300]
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

```Version: 0.11.0
Python: 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]
boto3 version: 1.9.159
Platform: Windows-10-10.0.18362
Config: {'output_timestamp_enabled': False, 'watch_interval': 1, 'end': None, 'log_group_name': '/aws/lambda/dialer-prod-getRecord', 'log_stream_name': 'ALL', 'output_group_enabled': True, 'color': 'auto', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': "'4h", 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'output_stream_enabled': True}
Args: ['C:\\Python27\\Scripts\\awslogs', 'get', '/aws/lambda/xxxxxxxxxxxx', "--start='4h", "ago'"]

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\awslogs\bin.py", line 178, in main
    getattr(logs, options.func)()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 223, in list_logs
    consumer()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 212, in consumer
    print(' '.join(output))
  File "c:\python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "c:\python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\x9d' in position 204: character maps to <undefined>

```

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
