### ISSUE TITLE
utilizing awslogs with aws-azure-login results in error - resolved

### ISSUE THREAD

**Issue by mfarra** [jorgebastida/awslogs#302]
We recently switched from hardcoded IAM profiles to AzureAD ephemeral AWS credentials via https://github.com/sportradar/aws-azure-login

awslogs can no longer parse my .aws/config file. It looks like aws-azure-login adds new data to each profile in .aws/config as in this example:

[profile wes-prod]
azure_tenant_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
azure_app_id_uri=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
azure_default_username=user@xample.com
azure_default_role_arn=
azure_default_duration_hours=5
azure_default_remember_me=true
region=us-east-1

Stack trace:

```Version: 0.11.0
Python: 3.8.2 (default, Jun  2 2020, 15:29:47)
[Clang 11.0.0 (clang-1100.0.33.8)]
boto3 version: 1.10.26
Platform: macOS-10.15.5-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': 'us-east-1', 'log_group_name': '/engage/utc/prod/moodle_cron', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}
Args: ['/Users/mfarra/.pyenv/versions/3.8.2/bin/awslogs', 'get', '/engage/utc/prod/moodle_cron', '--profile', 'wes-prod', '--aws-region', 'us-east-1', '--watch']

Traceback (most recent call last):
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configloader.py", line 149, in raw_config_parse
    cp.read([path])
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/Users/mfarra/.aws/config' [line 39]: option 'region' in section 'profile tlh-legacy' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/awslogs/core.py", line 84, in __init__
    self.client = boto3_client(
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/awslogs/core.py", line 38, in boto3_client
    credential_provider = core_session.get_component('credential_provider').get_provider('assume-role')
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 685, in get_component
    return self._components.get_component(name)
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 922, in get_component
    self._components[name] = factory()
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 148, in _create_credential_resolver
    return botocore.credentials.create_credential_resolver(
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/credentials.py", line 62, in create_credential_resolver
    metadata_timeout = session.get_config_variable('metadata_service_timeout')
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 238, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configprovider.py", line 231, in get_config_variable
    return provider.provide()
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configprovider.py", line 328, in provide
    value = provider.provide()
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configprovider.py", line 387, in provide
    config = self._session.get_scoped_config()
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 330, in get_scoped_config
    profile_map = self._build_profile_map()
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 224, in _build_profile_map
    self._profile_map = self.full_config['profiles']
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/session.py", line 357, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configloader.py", line 106, in load_config
    parsed = raw_config_parse(config_filename)
  File "/Users/mfarra/.pyenv/versions/3.8.2/lib/python3.8/site-packages/botocore/configloader.py", line 151, in raw_config_parse
    raise botocore.exceptions.ConfigParseError(
botocore.exceptions.ConfigParseError: Unable to parse config file: /Users/mfarra/.aws/config

```

**Comment by mfarra** [comment]
Issue was multiple region settings in the same profile. Closing.
