### ISSUE TITLE
Is "region" missing?

### ISSUE THREAD

**Issue by Saziba** [jorgebastida/awslogs#315]
Version:       0.14.0
Python:        3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]
boto3 version: 1.14.20
Platform:      macOS-10.15.6-x86_64-i386-64bit
Args:          ['/usr/local/bin/awslogs', 'get', '/aws-glue/jobs/output']
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': '/aws-glue/jobs/output', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/awslogs/bin.py", line 175, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/awslogs/core.py", line 89, in __init__
    self.client = boto3_client(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/awslogs/core.py", line 44, in boto3_client
    return session.client(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/session.py", line 831, in create_client
    client = client_creator.create_client(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 83, in create_client
    client_args = self._get_client_args(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 285, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 147, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 300, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 360, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/regions.py", line 133, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/local/Cellar/awslogs/0.14.0/libexec/lib/python3.8/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by BasilaryGroup** [comment]
You need to configure your AWS credential file. See [Configuration and credential file settings](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) and [here](https://github.com/jorgebastida/awslogs#how-to-provide-aws-credentials-to-awslogs).

`awslogs` will then find your AWS access key, secret access key, and region information automatically.
