### ISSUE TITLE
Found a bug while using "query"

### ISSUE THREAD

**Issue by davidcsi** [jorgebastida/awslogs#326]
```Version: 0.11.0
Python: 3.7.6 (default, Jan 23 2020, 18:04:24)
[Clang 11.0.0 (clang-1100.0.33.17)]
boto3 version: 1.9.62
Platform: Darwin-19.6.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/aws/containerinsights/massphoning-eks-cluster/application', 'log_stream_name': 'infra-voice-campaign-controller-c48d5bf96-z58c6_default_infra-voice-campaign-controller-cb69424c37db70ba86980283f73a7b912defcfd0c1021e4270bc75cdfcd1e407', 'filter_pattern': None, 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '2h ago', 'end': None, 'color': 'auto', 'query': 'uery=log', 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', '--watch', '--start=2h ago', '/aws/containerinsights/massphoning-eks-cluster/application', 'infra-voice-campaign-controller-c48d5bf96-z58c6_default_infra-voice-campaign-controller-cb69424c37db70ba86980283f73a7b912defcfd0c1021e4270bc75cdfcd1e407', '-query=log']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 174, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/awslogs/core.py", line 82, in __init__
    self.query_expression = jmespath.compile(self.query)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/jmespath/__init__.py", line 8, in compile
    return parser.Parser().parse(expression)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/jmespath/parser.py", line 109, in _parse
    self._tokens = list(self.tokenizer)
  File "/usr/local/Cellar/awslogs/0.11.0/libexec/lib/python3.7/site-packages/jmespath/lexer.py", line 105, in tokenize
    message="Unknown token '='")
jmespath.exceptions.LexerError: Bad jmespath expression: Unknown token '=':
uery=log
    ^

```%

**Comment by davidcsi** [comment]
nevermind... missing a dash
