### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character '\xb5' in position 279

### ISSUE THREAD

**Issue by d-tsuji** [jorgebastida/awslogs#336]
### Describe the bug

When I was examining the Lambda logs using awslogs and the grep command, the following exception was output.

```
C:\Users\d-tsuji>awslogs get /aws/lambda/sample-api  --start="3days ago" --profile test-profile --color never | grep report


You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

Version:       0.14.0
Python:        3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
boto3 version: 1.16.11
Platform:      Windows-10-10.0.18362-SP0
Args:          ['C:\\Users\\d-tsuji\\AppData\\Local\\Programs\\Python\\Python37\\Scripts\\awslogs', 'get', '/aws/lambda/sample-api', '--start=3days ago', '--profile', 'test-profile', '--color', 'never']
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': '/aws/lambda/sample-api', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '3days ago', 'end': None, 'color': 'never', 'query': None, 'func': 'list_logs'}

Traceback (most recent call last):
  File "c:\users\d-tsuji\appdata\local\programs\python\python37\lib\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "c:\users\d-tsuji\appdata\local\programs\python\python37\lib\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "c:\users\d-tsuji\appdata\local\programs\python\python37\lib\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
UnicodeEncodeError: 'cp932' codec can't encode character '\xb5' in position 279: illegal multibyte sequence
```

I would like your support.

**Comment by d-tsuji** [comment]
Tentatively, I installed awslogs on WSL and ran the same command, and the results were output without any exceptions. Thank you.
