### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 33: character maps to <undefined>

### ISSUE THREAD

**Issue by HybrisGit** [jorgebastida/awslogs#364]
```
Version:       0.14.0
Python:        3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
boto3 version: 1.20.18
Platform:      Windows-10-10.0.19043-SP0

Traceback (most recent call last):
  File "C:\Users\Lukas Lindberg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "C:\Users\Lukas Lindberg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "C:\Users\Lukas Lindberg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 33: character maps to <undefined>
```

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
