### ISSUE TITLE
botocore.exceptions.ConfigParseError: Unable to parse config file

### ISSUE THREAD

**Issue by chenleishen** [jorgebastida/awslogs#367]
```
λ awslogs -version


You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

Version:       0.14.0
Python:        3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
boto3 version: 1.20.48
Platform:      Windows-10-10.0.19042-SP0
Args:          ['C:\\Python310\\Scripts\\awslogs', '-version']
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE'}

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\botocore\configloader.py", line 149, in raw_config_parse
    cp.read([path])
  File "C:\Python310\lib\configparser.py", line 698, in read
    self._read(fp, filename)
  File "C:\Python310\lib\configparser.py", line 1097, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'C:\\Users\\[user_name_redacted]/.aws/credentials' [line  4]: option 'aws_access_key_id' in section 'terraforms3backend' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\awslogs\bin.py", line 175, in main
    logs = AWSLogs(**vars(options))
  File "C:\Python310\lib\site-packages\awslogs\core.py", line 89, in __init__
    self.client = boto3_client(
  File "C:\Python310\lib\site-packages\awslogs\core.py", line 39, in boto3_client
    credential_provider = core_session.get_component('credential_provider').get_provider('assume-role')
  File "C:\Python310\lib\site-packages\botocore\session.py", line 714, in get_component
    return self._components.get_component(name)
  File "C:\Python310\lib\site-packages\botocore\session.py", line 991, in get_component
    self._components[name] = factory()
  File "C:\Python310\lib\site-packages\botocore\session.py", line 153, in _create_credential_resolver
    return botocore.credentials.create_credential_resolver(
  File "C:\Python310\lib\site-packages\botocore\credentials.py", line 66, in create_credential_resolver
    metadata_timeout = session.get_config_variable('metadata_service_timeout')
  File "C:\Python310\lib\site-packages\botocore\session.py", line 267, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "C:\Python310\lib\site-packages\botocore\configprovider.py", line 374, in get_config_variable
    return provider.provide()
  File "C:\Python310\lib\site-packages\botocore\configprovider.py", line 567, in provide
    value = provider.provide()
  File "C:\Python310\lib\site-packages\botocore\configprovider.py", line 655, in provide
    scoped_config = self._session.get_scoped_config()
  File "C:\Python310\lib\site-packages\botocore\session.py", line 357, in get_scoped_config
    profile_map = self._build_profile_map()
  File "C:\Python310\lib\site-packages\botocore\session.py", line 253, in _build_profile_map
    self._profile_map = self.full_config['profiles']
  File "C:\Python310\lib\site-packages\botocore\session.py", line 394, in full_config
    cred_profiles = botocore.configloader.raw_config_parse(
  File "C:\Python310\lib\site-packages\botocore\configloader.py", line 151, in raw_config_parse
    raise botocore.exceptions.ConfigParseError(
botocore.exceptions.ConfigParseError: Unable to parse config file: C:\Users\[user_name_redacted]/.aws/credentials
```

**Comment by chenleishen** [comment]
`aws configure` didn't write to existing credential file correctly.

**Comment by chenleishen** [comment]
This was the incorrect format
```[]

**Comment by chenleishen** [comment]
This was the incorrect format

**Comment by chenleishen** [comment]
This was the incorrect format
```
[name_redacted]
aws_access_key_id = SENSITIVE
aws_secret_access_key = SENSITIVE[default]
aws_access_key_id = SENSITIVE
aws_secret_access_key = SENSITIVE
```
