### ISSUE TITLE
You've found a bug

### ISSUE THREAD

**Issue by tlong305** [jorgebastida/awslogs#400]
Version:       0.15.0
Python:        3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
boto3 version: 1.34.86
Platform:      Windows-11-10.0.22631-SP0

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python312\Lib\site-packages\awslogs\bin.py", line 210, in main
    getattr(logs, options.func)()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python312\Lib\site-packages\awslogs\core.py", line 219, in list_logs
    consumer()
  File "C:\Users\user1AppData\Local\Programs\Python\Python312\Lib\site-packages\awslogs\core.py", line 206, in consumer
    print(" ".join(output))
  File "C:\Users\user1\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1900-1905: character maps to <undefined>

**Comment by Balobanov** [comment]
The same issue with Win 11.

Version:       0.15.0
Python:        3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
boto3 version: 1.34.131
Platform:      Windows-10-10.0.22631-SP0

Sometimes it works, sometimes not.

**Comment by mtarleton-istation-21** [comment]
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

Version:       0.15.0
Python:        3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
boto3 version: 1.34.149
Platform:      Windows-11-10.0.22631-SP0
Args:          ['C:\\Python312\\Scripts\\awslogs', 'get', '/importservices/application/ImportService', '-s', '30m', '--filter-pattern=%[Ee]xception|[Ee]rror%', '--profile', 'istation.staging2']
Config: {options}

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\awslogs\bin.py", line 210, in main
    getattr(logs, options.func)()
  File "C:\Python312\Lib\site-packages\awslogs\core.py", line 219, in list_logs
    consumer()
  File "C:\Python312\Lib\site-packages\awslogs\core.py", line 206, in consumer
    print(" ".join(output))
  File "C:\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 426: character maps to <undefined>

**Comment by patylgoto** [comment]
Is this repository being maintained?
