### ISSUE TITLE
TypeError parsing date.

### ISSUE THREAD

**Issue by luqasz** [jorgebastida/awslogs#53]
Hi.

I've just noticed that passing `Wednesday 27 January, 2016 20:09:58 UTC` to `--start` and `--end` causes stack trace:
```
Traceback (most recent call last):
  File "/Users/lkostka/.virtualenvs/ansible/lib/python2.7/site-packages/awslogs/bin.py", line 138, in main
    logs = AWSLogs(**vars(options))
  File "/Users/lkostka/.virtualenvs/ansible/lib/python2.7/site-packages/awslogs/core.py", line 49, in __init__
    self.start = self.parse_datetime(kwargs.get('start'))
  File "/Users/lkostka/.virtualenvs/ansible/lib/python2.7/site-packages/awslogs/core.py", line 234, in parse_datetime
    return int(total_seconds(date - datetime(1970, 1, 1))) * 1000
TypeError: can't subtract offset-naive and offset-aware datetimes
``` 
Exact same string works in `dateutil`
```
In [1]: from dateutil.parser import parse

In [2]: parse("Wednesday 27 January, 2016 20:09:58 UTC")
Out[2]: datetime.datetime(2016, 1, 27, 20, 9, 58, tzinfo=tzutc())
```

**Comment by sjafferali** [comment]
I get this as well using the example in the documentation. Seems to be related to this bug. Posting the debug output for additional reference. 

```
[root@jump1 ~]# awslogs get /var/log/messages SENSITIVE --start 'Sat Aug 6 15:13:46 UTC 2016'

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.5.0
Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
boto3 version: 1.3.1
Platform: Linux-3.10.0-327.13.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': 'SENSITIVE', 'watch': False, 'aws_region': None, 'aws_session_token': 'SENSITIVE', 'start': 'Sat Aug 6 15:13:46 UTC 2016', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'log_group_name': '/var/log/messages', 'output_ingestion_time_enabled': False, 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/bin/awslogs', 'get', '/var/log/messages', 'SENSITIVE', '--start', 'Sat Aug 6 15:13:46 UTC 2016']

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 156, in main
    logs = AWSLogs(**vars(options))
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 52, in __init__
    self.start = self.parse_datetime(kwargs.get('start'))
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 256, in parse_datetime
    return int(total_seconds(date - datetime(1970, 1, 1))) * 1000
TypeError: can't subtract offset-naive and offset-aware datetimes
================================================================================
```

I also get this when specifying a time in the format "2PM CDT"

```
[root@jump1 ~]# awslogs get /var/log/messages SENSITIVE --start '2PM CDT'

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.5.0
Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
boto3 version: 1.3.1
Platform: Linux-3.10.0-327.13.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': 'SENSITIVE, 'watch': False, 'aws_region': None, 'aws_session_token': 'SENSITIVE', 'start': '2PM CDT', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'log_group_name': '/var/log/messages', 'output_ingestion_time_enabled': False, 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/bin/awslogs', 'get', '/var/log/messages', 'SENSITIVE', '--start', '2PM CDT']

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 156, in main
    logs = AWSLogs(**vars(options))
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 52, in __init__
    self.start = self.parse_datetime(kwargs.get('start'))
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 256, in parse_datetime
    return int(total_seconds(date - datetime(1970, 1, 1))) * 1000
TypeError: can't subtract offset-naive and offset-aware datetimes
================================================================================
```

However, as reported by @luqasz, these strings do work in dateutil. 

```
>>> from dateutil.parser import parse
>>> parse("Sat Aug 6 15:13:46 UTC 2016")
datetime.datetime(2016, 8, 6, 15, 13, 46, tzinfo=tzutc())
>>> parse("2PM CDT")
datetime.datetime(2016, 8, 6, 14, 0, tzinfo=tzlocal())
>>>
```

**Comment by jorgebastida** [comment]
This should not longer be a problem after https://github.com/jorgebastida/awslogs/pull/89

**Comment by luqasz** [comment]
It works now. Thx.
