### ISSUE TITLE
IOError: [Errno 32] Broken pipe in --watch option

### ISSUE THREAD

**Issue by Chintanvpatel** [jorgebastida/awslogs#80]
When i run awslogs with --watch option and keep it running, After some time i got below error,

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 132, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```

Regards,
Chintan Patel

**Comment by jorgebastida** [comment]
This issue might not present anymore after https://github.com/jorgebastida/awslogs/pull/87
