### ISSUE TITLE
Should catch EPIPE on standard output

### ISSUE THREAD

**Issue by mfischer-zd** [jorgebastida/awslogs#93]
When running `awslogs get $GROUP $STREAM | head`, the `EPIPE` exception is uncaught:

```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.7.0
Python: 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
boto3 version: 1.2.3
Platform: Darwin-15.6.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'xxxxxxxx', 'log_stream_name': 'xxxxxxxx', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'xxxxxx', 'yyyyy]

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 185, in consumer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```

"Broken pipe" errors on standard output should usually be caught and ignored.

**Comment by jamesmcintyre** [comment]
I wanted to pipe to sed to remove repetitive "prompt"-like text (would be a great option btw) and I got the broken pipe error as well. I tried EVERYTHING with stdbuf on osx but ultimately I think the issue is this broken pipe problem. This looks relevant: http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python

**Comment by jorgebastida** [comment]
Fixed https://github.com/jorgebastida/awslogs/pull/128
