### ISSUE TITLE
Providing stream as '*' errors out

### ISSUE THREAD

**Issue by AlJohri** [jorgebastida/awslogs#94]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.7.0
Python: 3.5.2 (default, Aug 16 2016, 05:35:40)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
boto3 version: 1.4.0
Platform: Darwin-15.6.0-x86_64-i386-64bit
Config: {'log_group_name': '/nile/perso.nile.works/heliograf-election2016-admin', 'output_stream_enabled': True, 'aws_secret_access_key': 'SENSITIVE', 'output_timestamp_enabled': False, 'log_stream_name': '*', 'aws_profile': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'aws_region': 'us-east-1', 'end': None, 'watch': True, 'func': 'list_logs', 'color_enabled': True, 'output_group_enabled': True, 'aws_access_key_id': 'SENSITIVE', 'query': None, 'filter_pattern': None, 'start': '10 min'}
Args: ['/Users/johria/.virtualenvs/heliograf/bin/awslogs', 'get', '/nile/perso.nile.works/heliograf-election2016-admin', '*', '--profile', 'main', '-s', '10 min', '--watch']

Traceback (most recent call last):
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/site-packages/awslogs/core.py", line 75, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/site-packages/awslogs/core.py", line 67, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/johria/.virtualenvs/heliograf/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 1
================================================================================

**Comment by sebsto** [comment]
Same error here 

Version: 0.7.0
Python: 3.5.2 (default, Jul 28 2016, 21:28:00)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
boto3 version: 1.4.1
Platform: Darwin-16.0.0-x86_64-i386-64bit
Config: {'output_stream_enabled': True, 'watch': False, 'aws_region': None, 'output_group_enabled': True, 'log_stream_name': '*', 'start': '5m', 'aws_session_token': 'SENSITIVE', 'filter_pattern': None, 'output_ingestion_time_enabled': False, 'aws_secret_access_key': 'SENSITIVE', 'func': 'list_logs', 'query': None, 'aws_access_key_id': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'color_enabled': True, 'log_group_name': 'API-Gateway-Execution-Logs_sdp9dj75b9/prod', 'output_timestamp_enabled': False, 'end': None}
Args: ['/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/bin/awslogs', 'get', 'API-Gateway-Execution-Logs_sdp9dj75b9/prod', '*']

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python3.5/site-packages/awslogs/core.py", line 75, in list_logs
    streams = list(self._get_streams_from_pattern(self.log_group_name, self.log_stream_name))
  File "/usr/local/lib/python3.5/site-packages/awslogs/core.py", line 67, in _get_streams_from_pattern
    reg = re.compile('^{0}'.format(pattern))
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 1
