### ISSUE TITLE
EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.ap-southeast-2.amazonaws.com/"

### ISSUE THREAD

**Issue by lailazouaki** [jorgebastida/awslogs#98]
```
Version: 0.7.0
Python: 2.7.11 (default, Mar 20 2016, 08:14:25) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
boto3 version: 1.4.1
Platform: Darwin-15.6.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'uat-app.log', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': True, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/Users/nrxl/dev/spence/service/.virtualenv/spence/bin/awslogs', 'get', '--watch', 'uat-app.log']

Traceback (most recent call last):
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/awslogs/bin.py", line 166, in main
    getattr(logs, options.func)()
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/awslogs/core.py", line 187, in list_logs
    consumer()
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/awslogs/core.py", line 136, in consumer
    for event in generator():
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/awslogs/core.py", line 123, in generator
    response = self.client.filter_log_events(**kwargs)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/nrxl/dev/spence/service/.virtualenv/spence/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.ap-southeast-2.amazonaws.com/"
```

**Comment by jorgebastida** [comment]
It looks like a connectivity issue and not an awslogs error perse.
